"""add total_marks to assignments

Revision ID: 1458f2f9bd04
Revises: f7cd1f1bde08
Create Date: 2026-06-08 13:55:21.340526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1458f2f9bd04'
down_revision: Union[str, Sequence[str], None] = 'f7cd1f1bde08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'assignments',
    sa.Column(
        'total_marks',
        sa.Integer(),
        nullable=False,
        server_default='100'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'total_marks')
    # ### end Alembic commands ###
